### ISSUE TITLE
Allow `PYPI_API_TOKEN` for Python

### ISSUE THREAD

**Issue by dehume** [pulumi/pulumi-package-publisher#17]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

### Affected area/feature

The `release.yml` Github Action in the deployment template for the boiler repo references `PYPI_API_TOKEN` in the [comments](https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/main/deployment-templates/release.yml#L22). However it does not seem that supplying just `PYPI_API_TOKEN` is allowed for Python deployments.

**Comment by dehume** [comment]
Not urgent, I just did not use `pulumi-package-publisher` for my deployment Github Action for now

**Comment by ingridcrant** [comment]
Is this feature request resolved with this PR https://github.com/pulumi/pulumi/pull/15048?

**Comment by mjeffryes** [comment]
It's not resolved exactly as the original requestor asked, but it's true that this package dose support using tokens by using `__token__` for the `PYPI_USERNAME` and actual token in the `PYPI_PASSWORD` parameter. We should probably add a comment to that effect.
